### ISSUE TITLE
a space in package.xml cause rosdep install and catkin build fail

### ISSUE THREAD

**Issue by leonidas141** [vittoriocataffo/A-Nonlinear-Model-Predictive-Control-Strategy-for-Autonomous-Racing-of-Scale-Vehicles#3]
Please check the email address in <code>package.xml#L10</code>.
The space after the email cause errors: 
> Invalid email "vittorio.cataffo@gmail.com " for person "Vittorio Cataffo"

when trying to rosdep install or catkin build.
Delete the space will fix the problem.

**Comment by gsilano** [comment]
Hi! Fixed with the latest commit. See, and let me know.

**Comment by leonidas141** [comment]
Hi! The latest commit fixed it, nice work, thank you!
