### ISSUE TITLE
ros2 version code

### ISSUE THREAD

**Issue by Zhu0917** [vittoriocataffo/A-Nonlinear-Model-Predictive-Control-Strategy-for-Autonomous-Racing-of-Scale-Vehicles#4]
awesome work! but i am wondering that is there have ros2 version code now? :)

**Comment by gsilano** [comment]
Thank you for your kind words! At the moment, we don't have plans to release a ROS2 version in the short term. However, we're open to any suggestions or assistance if you're interested in contributing toward this effort. Let us know if you'd like to discuss this further! 😊

**Comment by Zhu0917** [comment]
Thanks for your reply, I am trying to build a ROS2 HUMBLE based f1tenth race car for testing vehicle stability control issues at high speeds, so I'm looking for a copy of the open source code to improve it, and so far I've only seen your  code, and I've seen that the code is written in python, so may I ask if I rewrite it in ros2 and c++, will it make the If I use ros2 and c++ to rewrite it, will it improve the performance? Also I am using the official f1tenth racing car model traxxas series, do you know how to get the dynamics parameters of this car, do you have any thesis or method to refer to, thank you!

**Comment by gsilano** [comment]
I understand your issue. I'm not sure if a ROS2 version of the F1TENTH simulator is available. You might consider opening an issue on their GitHub repository. From what I can see, the end-user instructions in the repository are still based on Ubuntu 18.04.

If I understand correctly, you're considering rewriting our code in ROS2 and C++ to improve performance. Performance improvements largely depend on the solver, as it’s an NMPC problem that relies on the [OpEn framework](https://alphaville.github.io/optimization-engine/). Although I haven’t looked into it recently, if you’ve found new features with ROS2, rewriting could potentially offer slight performance improvements for our proposed algorithm.

As for the car parameters, I’m not familiar with how to obtain them. You may need to contact the car’s designer for that information.

**Comment by Zhu0917** [comment]
Thank you for your attentive reply.
